<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);NU5128;NU5100</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Whipstaff.Markdig" Version="9.1.205" />
  </ItemGroup>
</Project>
